--liquibase formatted sql
--changeset Marek:260717-07a
--comment Drop old operation constraints and align primary key constraint names
ALTER TABLE OPERATION DROP CONSTRAINT OPERATION_CHK;
ALTER TABLE OPERATION DROP CONSTRAINT REGISTER_OPERATIONS_FROM_FK;
ALTER TABLE OPERATION DROP CONSTRAINT REGISTER_OPERATIONS_TO_FK;
ALTER TABLE REGISTER RENAME CONSTRAINT REGISTER_PK TO REGISTERS_PK;
ALTER TABLE OPERATION RENAME CONSTRAINT OPERATION_PK TO OPERATIONS_PK;
--rollback ALTER TABLE OPERATION RENAME CONSTRAINT OPERATIONS_PK TO OPERATION_PK;
--rollback ALTER TABLE REGISTER RENAME CONSTRAINT REGISTERS_PK TO REGISTER_PK;
--rollback ALTER TABLE OPERATION ADD CONSTRAINT REGISTER_OPERATIONS_TO_FK FOREIGN KEY (OPERATIONS_TO) REFERENCES REGISTER (ID);
--rollback ALTER TABLE OPERATION ADD CONSTRAINT REGISTER_OPERATIONS_FROM_FK FOREIGN KEY (OPERATIONS_FROM) REFERENCES REGISTER (ID);
--rollback ALTER TABLE OPERATION ADD CONSTRAINT OPERATION_CHK CHECK (OPERATION.OPERATIONS_FROM IS NOT NULL OR OPERATION.OPERATIONS_TO IS NOT NULL);
